name: "Create a comment on new issues"

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event)}}' | jq
        shell: bash 
      - name: "Create comment"
        uses: "peter-evans/create-or-update-comment@v4"
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          issue-number: '${{ github.event.issue.number}}'
          body: |
            Hello, we will get to you shortly
            Have a nice day
          reactions: '+1'

          
